const SUPABASE_URL='https://bkxpeycpqphskjpgimsj.supabase.co';const SUPABASE_KEY='sb_publishable_v9KFnlmn-BJsZrs2CDLrsw_NUCAkVZy';const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let settings={siteName:'𝐀𝐇𝐀𝐃 𝐁𝐇𝐀𝐈 𝐒𝐊𝐈𝐋𝐋 𝐋𝐀𝐁',heroTitle:'Learn. Create. Grow Online.',heroText:'I am ABDUL AHEAD. I teach AI video creation, social media skills, captions, hashtags, video creation and promotion — all online.',aboutTitle:'ABDUL AHEAD',aboutText:'I teach everything online.',logo:'logo.jpg',banner:'banner.jpg',profile:'profile.jpg',topics:[],socials:[],contact:[]};
function setTheme(t){document.body.dataset.theme=t;localStorage.setItem('ahl_theme',t)}setTheme(localStorage.getItem('ahl_theme')||'light');
async function adminLogin(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,msg=document.getElementById('loginMsg');if(!email||!password){msg.textContent='Enter your admin email and password.';return}const {error}=await sb.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return}showDash()}
async function showDash(){document.getElementById('login').style.display='none';document.getElementById('dash').classList.add('show');await loadSettingsIntoEditor();await loadAnalytics()}
async function adminLogout(){await sb.auth.signOut();location.reload()}
function tab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active')}
async function loadSettings(){const {data}=await sb.from('site_settings').select('data').eq('id','site').maybeSingle();if(data?.data)settings={...settings,...data.data};return settings}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadSettingsIntoEditor(){await loadSettings();document.getElementById('siteNameInput').value=settings.siteName||'';document.getElementById('heroTitleInput').value=settings.heroTitle||'';document.getElementById('heroTextInput').value=settings.heroText||'';document.getElementById('aboutTitleInput').value=settings.aboutTitle||'';document.getElementById('aboutTextInput').value=settings.aboutText||'';document.getElementById('logoInput').value=settings.logo||'';document.getElementById('bannerInput').value=settings.banner||'';document.getElementById('profileInput').value=settings.profile||'';renderTutorialEditor();renderSocialEditor();renderContactEditor()}
function renderTutorialEditor(){document.getElementById('tutorialEditor').innerHTML=(settings.topics||[]).map((t,i)=>`<div class="repeat-item"><div class="row"><div class="field"><label>Title</label><input data-t="${i}" data-k="title" value="${esc(t.title)}"></div><div class="field"><label>Icon</label><input data-t="${i}" data-k="icon" value="${esc(t.icon||'▶')}"></div></div><div class="field"><label>Description</label><textarea data-t="${i}" data-k="desc">${esc(t.desc||'')}</textarea></div><div class="field"><label>Direct Link / Video URL</label><input data-t="${i}" data-k="url" value="${esc(t.url||'')}"></div><button class="btn danger" onclick="removeTutorial(${i})">Delete</button></div>`).join('')||'<div class="notice">No tutorials yet. Tap Add Tutorial.</div>'}
function renderSocialEditor(){document.getElementById('socialEditor').innerHTML=(settings.socials||[]).map((s,i)=>`<div class="repeat-item"><div class="row"><div class="field"><label>Name</label><input data-s="${i}" data-k="title" value="${esc(s.title)}"></div><div class="field"><label>Icon</label><input data-s="${i}" data-k="icon" value="${esc(s.icon||'◎')}"></div></div><div class="field"><label>Link</label><input data-s="${i}" data-k="url" value="${esc(s.url||'')}"></div><div class="field"><label>Button Text</label><input data-s="${i}" data-k="button" value="${esc(s.button||'Open →')}"></div><button class="btn danger" onclick="removeSocial(${i})">Delete</button></div>`).join('')}
function renderContactEditor(){document.getElementById('contactEditor').innerHTML=(settings.contact||[]).map((c,i)=>`<div class="repeat-item"><div class="row"><div class="field"><label>Title</label><input data-c="${i}" data-k="title" value="${esc(c.title)}"></div><div class="field"><label>Icon</label><input data-c="${i}" data-k="icon" value="${esc(c.icon||'✉')}"></div></div><div class="field"><label>Description</label><input data-c="${i}" data-k="desc" value="${esc(c.desc||'')}"></div><div class="row"><div class="field"><label>Link</label><input data-c="${i}" data-k="url" value="${esc(c.url||'')}"></div><div class="field"><label>Button Text</label><input data-c="${i}" data-k="button" value="${esc(c.button||'Open →')}"></div></div><button class="btn danger" onclick="removeContact(${i})">Delete</button></div>`).join('')}
function addTutorial(){settings.topics.push({id:'t-'+Date.now(),title:'New Tutorial',desc:'Add a description.',icon:'▶',url:'https://'});renderTutorialEditor()};function removeTutorial(i){settings.topics.splice(i,1);renderTutorialEditor()};function addSocial(){settings.socials.push({id:'s-'+Date.now(),title:'New Social Link',icon:'◎',url:'https://',button:'Open →'});renderSocialEditor()};function removeSocial(i){settings.socials.splice(i,1);renderSocialEditor()};function addContact(){settings.contact.push({title:'New Contact',icon:'✉',desc:'',url:'https://',button:'Open →'});renderContactEditor()};function removeContact(i){settings.contact.splice(i,1);renderContactEditor()}
function collect(){['topics','socials','contact'].forEach(type=>{document.querySelectorAll(`[data-${type==='topics'?'t':type==='socials'?'s':'c'}]`).forEach(el=>{const i=+el.dataset[type==='topics'?'t':type==='socials'?'s':'c'],k=el.dataset.k;settings[type][i][k]=el.value})});settings.siteName=document.getElementById('siteNameInput').value;settings.heroTitle=document.getElementById('heroTitleInput').value;settings.heroText=document.getElementById('heroTextInput').value;settings.aboutTitle=document.getElementById('aboutTitleInput').value;settings.aboutText=document.getElementById('aboutTextInput').value;settings.logo=document.getElementById('logoInput').value||'logo.jpg';settings.banner=document.getElementById('bannerInput').value||'banner.jpg';settings.profile=document.getElementById('profileInput').value||'profile.jpg'}
async function saveAll(){collect();const {error}=await sb.from('site_settings').upsert({id:'site',data:settings,updated_at:new Date().toISOString()});alert(error?'Save failed: '+error.message:'Saved and published successfully. Open the website to see the changes.');}
async function uploadMedia(){const f=document.getElementById('mediaFile').files[0],msg=document.getElementById('uploadMsg');if(!f){msg.textContent='Choose a file first.';return}const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path='site-media/'+Date.now()+'-'+safe;const {error}=await sb.storage.from('site-media').upload(path,f,{upsert:false});if(error){msg.textContent=error.message;return}const {data}=sb.storage.from('site-media').getPublicUrl(path);msg.innerHTML='Uploaded. Public URL: <input style="width:100%;padding:10px;margin-top:8px" value="'+esc(data.publicUrl)+'" readonly>';}
async function loadAnalytics(){const now=Date.now();const five=new Date(now-5*60000).toISOString();const {data:events}=await sb.from('site_events').select('event_type,session_id,tutorial_id,created_at,metadata').gte('created_at',new Date(now-30*86400000).toISOString()).order('created_at',{ascending:false}).limit(5000);const e=events||[];const online=new Set(e.filter(x=>x.event_type==='presence'&&x.created_at>=five).map(x=>x.session_id).filter(Boolean)).size;document.getElementById('online').textContent=online;document.getElementById('views').textContent=e.filter(x=>x.event_type==='page_view').length;document.getElementById('tutorialViews').textContent=e.filter(x=>x.event_type==='tutorial_view').length;document.getElementById('socialClicks').textContent=e.filter(x=>x.event_type==='social_click').length;const days={};for(let i=6;i>=0;i--){const d=new Date(now-i*86400000);const key=d.toISOString().slice(0,10);days[key]=0}e.filter(x=>x.event_type==='page_view').forEach(x=>{const k=x.created_at.slice(0,10);if(k in days)days[k]++});const max=Math.max(1,...Object.values(days));document.getElementById('daily').innerHTML=Object.entries(days).map(([d,v])=>`<div><b>${d}</b> <span>${v} views</span><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join('');const top={};e.filter(x=>x.event_type==='tutorial_view').forEach(x=>{const k=x.tutorial_id||'unknown';top[k]=(top[k]||0)+1});document.getElementById('topTutorials').innerHTML=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v])=>`<div class="notice"><b>${esc(k)}</b> — ${v} views</div>`).join('')||'<div class="notice">No tutorial views yet.</div>'}
(async()=>{const {data:{session}}=await sb.auth.getSession();if(session)showDash()})();
