const SUPABASE_URL='https://bkxpeycpqphskjpgimsj.supabase.co';
const SUPABASE_KEY='sb_publishable_v9KFnlmn-BJsZrs2CDLrsw_NUCAkVZy';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const topics=[['AI Video Creation','Create AI-powered videos step by step.'],['Thumbnail Design','Make attractive thumbnails for your videos.'],['Hashtags','Learn how to choose and use hashtags.'],['Captions','Write better captions for social posts.'],['Location','Use location correctly on Facebook and YouTube posts.'],['Video Creation','Learn practical video creation techniques.'],['Facebook','Learn useful Facebook content and posting tips.'],['YouTube','Learn YouTube video and channel basics.'],['Video Promotion','Learn ways to promote your videos.']];
const channel='https://t.me/+VeysP6zpQI9kZTJl';
const socials=[['Telegram Personal','✈️','https://t.me/Aheadvia1298','Message Me →'],['Telegram Channel','📣',channel,'Join Channel →'],['Telegram Group','👥','https://t.me/+po7cNT2DyokwMzQ1','Join Group →'],['Facebook','f','https://www.facebook.com/share/199T5uSBXv/','Follow Facebook →'],['Instagram','◎','https://www.instagram.com/kittysnipsofficial?stkn=MW44cGFpYWNkc3F5bQ==','Follow Instagram →'],['YouTube','▶','https://www.youtube.com/@KittySnipsStories','Watch YouTube →'],['TikTok','♪','https://www.tiktok.com/@abdulahead121','Follow TikTok →'],['X / Twitter','𝕏','https://x.com/Abdulaheadrllm','Follow X →']];
let mode='login', current=null, avatarData='';
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(page).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'});}
function openAuth(m){mode=m;document.getElementById('auth').classList.add('show');document.getElementById('signupFields').style.display=m==='signup'?'grid':'none';document.getElementById('authTitle').innerHTML='<h2>'+ (m==='signup'?'Create Your Account':'Login to Your Account') +'</h2>';document.getElementById('authBtn').textContent=m==='signup'?'Create Account':'Login';document.getElementById('authSwitch').innerHTML=m==='signup'?'Already have an account? <button class="btn small ghost" onclick="openAuth(\'login\')">Login</button>':'New here? <button class="btn small ghost" onclick="openAuth(\'signup\')">Create Account</button>';document.getElementById('authMsg').textContent='';}
function closeAuth(){document.getElementById('auth').classList.remove('show')}
function syntheticEmail(u){return u.toLowerCase().replace(/[^a-z0-9_]/g,'')+'@ahadbhai-skill-lab.local'}
async function submitAuth(){const u=document.getElementById('authUsername').value.trim();const p=document.getElementById('authPassword').value;const msg=document.getElementById('authMsg');msg.className='';if(!u||!p)return msg.textContent='Username and password are required.';if(p.length<6)return msg.textContent='Password must be at least 6 characters.';if(mode==='signup'){const name=document.getElementById('authName').value.trim();if(!name)return msg.textContent='Please enter your name.';const email=syntheticEmail(u);const {data,error}=await sb.auth.signUp({email,password:p});if(error)return msg.textContent=error.message;const user=data.user;if(!user)return msg.textContent='Account could not be created.';const uid='AHL-'+user.id.replace(/-/g,'').slice(0,8).toUpperCase();const {error:pe}=await sb.from('profiles').insert({id:user.id,user_id:uid,name,username:u,bio:'',avatar_url:''});if(pe && !pe.message.includes('duplicate')){msg.textContent=pe.message;return}msg.className='ok';msg.textContent='Account created. Opening your website...';current={id:user.id,name,username:u,bio:'',user_id:uid,avatar_url:''};setTimeout(()=>{closeAuth();enterSite()},700)}else{const email=syntheticEmail(u);const {data,error}=await sb.auth.signInWithPassword({email,password:p});if(error)return msg.textContent='Login failed. Check your username and password.';msg.className='ok';msg.textContent='Login successful.';setTimeout(()=>{closeAuth();enterSite()},400)}}
async function enterSite(){document.getElementById('welcome').style.display='none';document.getElementById('topLogin').style.display='none';await loadProfile();go('home');track('page_view',{path:'/'});}
async function loadProfile(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(data)current=data;else current={id:user.id,name:'ABDUL AHEAD',username:'',bio:'',user_id:'AHL-'+user.id.slice(0,8).toUpperCase(),avatar_url:''};document.getElementById('setName').value=current.name||'';document.getElementById('setUsername').value=current.username||'';document.getElementById('setBio').value=current.bio||'';document.getElementById('userIdBox').textContent='Your Unique User ID: '+current.user_id;if(current.avatar_url)document.getElementById('avatarPreview').src=current.avatar_url}
async function saveSettings(){if(!current)return;const patch={name:document.getElementById('setName').value.trim(),username:document.getElementById('setUsername').value.trim(),bio:document.getElementById('setBio').value.trim(),avatar_url:avatarData||current.avatar_url||''};const np=document.getElementById('setPassword').value;if(!patch.name||!patch.username)return alert('Name and username are required.');const {error}=await sb.from('profiles').update(patch).eq('id',current.id);if(error)return alert(error.message);if(np){const {error:e}=await sb.auth.updateUser({password:np});if(e)return alert(e.message)}current={...current,...patch};document.getElementById('setPassword').value='';avatarData='';alert('Settings saved successfully.');track('profile_update',{});}
function previewAvatar(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{avatarData=r.result;document.getElementById('avatarPreview').src=r.result};r.readAsDataURL(f)}
async function logout(){await sb.auth.signOut();current=null;document.getElementById('welcome').style.display='grid';document.getElementById('topLogin').style.display='inline-flex';go('home')}
function renderTutorials(){document.getElementById('tutorialGrid').innerHTML=topics.map((t,i)=>`<div class="card tutorial-card" data-title="${t[0].toLowerCase()}"><h3>${t[0]}</h3><p>${t[1]}</p><a class="btn primary" href="${channel}" target="_blank" onclick="track('tutorial_view',{tutorial_id:'${i+1}'})">Open Tutorial →</a></div>`).join('')}
function filterTutorials(){const q=document.getElementById('search').value.toLowerCase();document.querySelectorAll('.tutorial-card').forEach(x=>x.style.display=x.dataset.title.includes(q)?'block':'none')}
function renderSocials(){document.getElementById('socialGrid').innerHTML=socials.map(s=>`<div class="card"><div class="big-icon">${s[1]}</div><h3>${s[0]}</h3><a class="btn primary" href="${s[2]}" target="_blank" onclick="track('social_click',{name:'${s[0]}'})">${s[3]}</a></div>`).join('')}
async function track(type,metadata={}){try{const {data:{user}}=await sb.auth.getUser();await sb.from('site_events').insert({event_type:type,user_id:user?.id||null,session_id:sessionStorage.getItem('ahl_session')||null,path:location.pathname,tutorial_id:metadata.tutorial_id||null,metadata})}catch(e){}}
async function boot(){renderTutorials();renderSocials();if(!sessionStorage.getItem('ahl_session'))sessionStorage.setItem('ahl_session',crypto.randomUUID?.()||String(Date.now()));const {data:{session}}=await sb.auth.getSession();if(session){await enterSite()}else{document.getElementById('welcome').style.display='grid'}}
boot();
