const SUPABASE_URL='https://bkxpeycpqphskjpgimsj.supabase.co';
const SUPABASE_KEY='sb_publishable_v9KFnlmn-BJsZrs2CDLrsw_NUCAkVZy';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const defaultSettings={siteName:'𝐀𝐇𝐀𝐃 𝐁𝐇𝐀𝐈 𝐒𝐊𝐈𝐋𝐋 𝐋𝐀𝐁',heroTitle:'Learn. Create. Grow Online.',heroText:'I am ABDUL AHEAD. I teach AI video creation, social media skills, captions, hashtags, video creation and promotion — all online.',aboutTitle:'ABDUL AHEAD',aboutText:'I teach everything online and share practical skills for AI, video creation and social media.',logo:'logo.jpg',banner:'banner.jpg',profile:'profile.jpg',topics:[
{id:'ai-video',title:'AI Video Creation',desc:'Create AI-powered videos step by step.',icon:'🤖',url:'https://t.me/+VeysP6zpQI9kZTJl'},
{id:'thumbnail',title:'Thumbnail Design',desc:'Make attractive thumbnails for your videos.',icon:'🖼️',url:'https://t.me/+VeysP6zpQI9kZTJl'},
{id:'hashtags',title:'Hashtags',desc:'Learn how to choose and use hashtags.',icon:'#️⃣',url:'https://t.me/+VeysP6zpQI9kZTJl'},
{id:'captions',title:'Captions',desc:'Write better captions for social posts.',icon:'✍️',url:'https://t.me/+VeysP6zpQI9kZTJl'},
{id:'location',title:'Location',desc:'Use location correctly on Facebook and YouTube posts.',icon:'📍',url:'https://t.me/+VeysP6zpQI9kZTJl'},
{id:'video-creation',title:'Video Creation',desc:'Learn practical video creation techniques.',icon:'🎬',url:'https://t.me/+VeysP6zpQI9kZTJl'},
{id:'facebook',title:'Facebook',desc:'Learn useful Facebook content and posting tips.',icon:'f',url:'https://www.facebook.com/share/199T5uSBXv/'},
{id:'youtube',title:'YouTube',desc:'Learn YouTube video and channel basics.',icon:'▶',url:'https://www.youtube.com/@KittySnipsStories'},
{id:'promotion',title:'Video Promotion',desc:'Learn ways to promote your videos.',icon:'🚀',url:'https://t.me/+VeysP6zpQI9kZTJl'}],
socials:[
{id:'telegram-personal',title:'Telegram Personal',icon:'✈️',url:'https://t.me/Aheadvia1298',button:'Message Me →'},
{id:'telegram-channel',title:'Telegram Channel',icon:'📣',url:'https://t.me/+VeysP6zpQI9kZTJl',button:'Join Channel →'},
{id:'telegram-group',title:'Telegram Group',icon:'👥',url:'https://t.me/+po7cNT2DyokwMzQ1',button:'Join Group →'},
{id:'facebook',title:'Facebook',icon:'f',url:'https://www.facebook.com/share/199T5uSBXv/',button:'Follow Facebook →'},
{id:'instagram',title:'Instagram',icon:'◎',url:'https://www.instagram.com/kittysnipsofficial?stkn=MW44cGFpYWNkc3F5bQ==',button:'Follow Instagram →'},
{id:'youtube',title:'YouTube',icon:'▶',url:'https://www.youtube.com/@KittySnipsStories',button:'Watch YouTube →'},
{id:'tiktok',title:'TikTok',icon:'♪',url:'https://www.tiktok.com/@abdulahead121',button:'Follow TikTok →'},
{id:'x',title:'X / Twitter',icon:'𝕏',url:'https://x.com/Abdulaheadrllm',button:'Follow X →'}],
contact:[{title:'Contact Me',icon:'📞',desc:'Open your phone contact app.',url:'tel:01335611366',button:'Contact Me →',type:'phone'},{title:'WhatsApp Message',icon:'💬',desc:'Start a private WhatsApp chat.',url:'https://wa.me/8801400524877',button:'WhatsApp Message →',type:'whatsapp'},{title:'Telegram Channel',icon:'📣',desc:'Join the official learning channel.',url:'https://t.me/+VeysP6zpQI9kZTJl',button:'Join Channel →'},{title:'Telegram Group',icon:'👥',desc:'Join the community group.',url:'https://t.me/+po7cNT2DyokwMzQ1',button:'Join Group →'}]};
let settings={...defaultSettings};
const sessionKey='ahl_session';
function sid(){let s=sessionStorage.getItem(sessionKey);if(!s){s=(crypto.randomUUID?crypto.randomUUID():String(Date.now()));sessionStorage.setItem(sessionKey,s)}return s}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const id=page==='about'?'aboutPage':page;const el=document.getElementById(id);if(el)el.classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'});track('page_view',{page});}
function setTheme(t){document.body.dataset.theme=t==='light'?'light':t;localStorage.setItem('ahl_theme',t);track('theme_change',{theme:t})}
function filterTutorials(){const q=(document.getElementById('search').value||'').toLowerCase();document.querySelectorAll('#tutorialGrid .tutorial-card').forEach(c=>c.style.display=c.dataset.search.includes(q)?'flex':'none')}
function tutorialCard(t){return `<article class="card tutorial-card" data-search="${esc((t.title+' '+t.desc).toLowerCase())}"><div class="icon">${esc(t.icon||'▶')}</div><h3>${esc(t.title)}</h3><p>${esc(t.desc)}</p><a class="btn primary" href="${esc(t.url||'#')}" target="_blank" rel="noopener" onclick="track('tutorial_view',{tutorial_id:'${esc(t.id||t.title)}'})">Open Tutorial →</a></article>`}
function render(){document.title=settings.siteName;document.getElementById('siteName').textContent=settings.siteName;document.getElementById('footerName').textContent=settings.siteName;document.getElementById('siteLogo').src=settings.logo||'logo.jpg';document.getElementById('heroBanner').src=settings.banner||'banner.jpg';document.getElementById('aboutPhoto').src=settings.profile||'profile.jpg';document.getElementById('heroTitle').textContent=settings.heroTitle;document.getElementById('heroText').textContent=settings.heroText;document.getElementById('aboutTitle').textContent=settings.aboutTitle;document.getElementById('aboutText').textContent=settings.aboutText;document.getElementById('aboutPageName').textContent=settings.aboutTitle;document.getElementById('aboutPageText').textContent=settings.aboutText;document.getElementById('topicCount').textContent=(settings.topics?.length||0)+'+';const cards=(settings.topics||[]).map(tutorialCard).join('');document.getElementById('homeTutorialGrid').innerHTML=cards;document.getElementById('tutorialGrid').innerHTML=cards;document.getElementById('socialGrid').innerHTML=(settings.socials||[]).map(s=>`<article class="card"><div class="social-icon">${esc(s.icon||'◎')}</div><h3>${esc(s.title)}</h3><a class="btn primary" href="${esc(s.url||'#')}" target="_blank" rel="noopener" onclick="track('social_click',{name:'${esc(s.id||s.title)}'})">${esc(s.button||'Open →')}</a></article>`).join('');document.getElementById('contactGrid').innerHTML=(settings.contact||[]).map(c=>`<article class="card"><div class="social-icon">${esc(c.icon||'✉')}</div><h3>${esc(c.title)}</h3><p>${esc(c.desc||'')}</p><a class="btn ${c.type==='whatsapp'?'green':'gold'}" href="${esc(c.url||'#')}" target="_blank" rel="noopener" onclick="track('contact_click',{type:'${esc(c.type||c.title)}'})">${esc(c.button||'Open →')}</a></article>`).join('')}
async function loadSettings(){try{const {data,error}=await sb.from('site_settings').select('data').eq('id','site').maybeSingle();if(!error&&data?.data)settings={...defaultSettings,...data.data}}catch(e){}render()}
async function track(type,metadata={}){try{await sb.from('site_events').insert({event_type:type,user_id:null,session_id:sid(),path:location.pathname,tutorial_id:metadata.tutorial_id||null,metadata})}catch(e){}}
async function presence(){await track('presence',{});setInterval(()=>track('presence',{}),45000)}
(async function(){setTheme(localStorage.getItem('ahl_theme')||'light');await loadSettings();await track('page_view',{page:'home'});presence()})();
