const SUPABASE_URL='https://bkxpeycpqphskjpgimsj.supabase.co';
const SUPABASE_KEY='sb_publishable_v9KFnlmn-BJsZrs2CDLrsw_NUCAkVZy';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const defaults={about:'I teach everything online.',tutorials:[['AI Video Creation','AI video creation and practical tools'],['Thumbnail Design','Create attractive thumbnails'],['Hashtags','Learn how to use hashtags'],['Captions','Write better captions'],['Location','Use location on Facebook and YouTube'],['Video Creation','Create videos step by step'],['Facebook','Learn Facebook content skills'],['YouTube','Learn YouTube content skills'],['Video Promotion','Promote videos effectively']],social:[['Telegram Personal','https://t.me/Aheadvia1298','✈️'],['Telegram Channel','https://t.me/+VeysP6zpQI9kZTJl','📢'],['Telegram Group','https://t.me/+po7cNT2DyokwMzQ1','👥'],['Facebook','https://www.facebook.com/share/199T5uSBXv/','f'],['Instagram','https://www.instagram.com/kittysnipsofficial?stkn=MW44cGFpYWNkc3F5bQ==','◎'],['YouTube','https://www.youtube.com/@KittySnipsStories','▶'],['TikTok','https://www.tiktok.com/@abdulahead121','♪'],['X','https://x.com/Abdulaheadrllm','𝕏']]};
let authMode='signup', profile={};
function openAuth(mode){authMode=mode;document.getElementById('auth').classList.add('show');renderAuth()}
function closeAuth(){document.getElementById('auth').classList.remove('show')}
function toggleAuth(){authMode=authMode==='signup'?'login':'signup';renderAuth()}
function renderAuth(){let signup=authMode==='signup';document.getElementById('authTitle').textContent=signup?'Create Account':'Login';document.getElementById('signupFields').style.display=signup?'block':'none';document.getElementById('authBtn').textContent=signup?'Create Account':'Login';document.getElementById('switchAuth').textContent=signup?'Already have an account? Login':'New here? Create Account';document.getElementById('authHint').textContent=signup?'Use your name, unique username and password. No phone, OTP, Google or email login.':'';}
function fakeEmail(u){return u.trim().toLowerCase().replace(/[^a-z0-9._-]/g,'')+'@users.ahadbhai-skill-lab.local'}
async function submitAuth(){const u=document.getElementById('authUsername').value.trim();const p=document.getElementById('authPassword').value;if(!u||!p)return alert('Enter username and password.');if(authMode==='signup'){const n=document.getElementById('signupName').value.trim();if(!n)return alert('Enter your name.');const {data,error}=await sb.auth.signUp({email:fakeEmail(u),password:p,options:{data:{display_name:n,username:u}}});if(error)return alert(error.message);if(data.user){await sb.from('user_profiles').upsert({id:data.user.id,email:fakeEmail(u),display_name:n,username:u,bio:'',public_user_id:'AHL-'+data.user.id.slice(0,8).toUpperCase()},{onConflict:'id'});}closeAuth();await loadUser();document.getElementById('welcome').style.display='none';showSection('home');alert('Account created successfully.')}else{const {error}=await sb.auth.signInWithPassword({email:fakeEmail(u),password:p});if(error)return alert('Login failed: '+error.message);closeAuth();await loadUser();document.getElementById('welcome').style.display='none';showSection('home')}}
async function loadUser(){const {data:{user}}=await sb.auth.getUser();if(!user){document.getElementById('welcome').style.display='flex';return}const {data}=await sb.from('user_profiles').select('*').eq('id',user.id).maybeSingle();profile=data||{id:user.id,display_name:user.user_metadata?.display_name||'User',username:user.user_metadata?.username||'',public_user_id:'AHL-'+user.id.slice(0,8).toUpperCase(),bio:''};document.getElementById('welcome').style.display='none';document.getElementById('userMini').textContent=profile.display_name||profile.username||'Account';document.getElementById('profileName').textContent=profile.display_name||profile.username||'Profile';document.getElementById('profileId').textContent='ID: '+(profile.public_user_id||'AHL-'+user.id.slice(0,8).toUpperCase());document.getElementById('nameInput').value=profile.display_name||'';document.getElementById('usernameInput').value=profile.username||'';document.getElementById('bioInput').value=profile.bio||'';if(profile.avatar_url){document.getElementById('profilePreview').src=profile.avatar_url;document.getElementById('avatarMini').textContent='';document.getElementById('avatarMini').style.backgroundImage=`url(${profile.avatar_url})`;document.getElementById('avatarMini').style.backgroundSize='cover';document.getElementById('avatarMini').style.width='25px';document.getElementById('avatarMini').style.height='25px';document.getElementById('avatarMini').style.borderRadius='50%'}}
async function saveProfile(){const {data:{user}}=await sb.auth.getUser();if(!user)return openAuth('login');let avatar_url=profile.avatar_url||'';const file=document.getElementById('avatarFile').files[0];if(file){const ext=file.name.split('.').pop().toLowerCase();const path=user.id+'/avatar.'+ext;const up=await sb.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type});if(up.error)return alert('Photo upload failed: '+up.error.message);avatar_url=sb.storage.from('avatars').getPublicUrl(path).data.publicUrl}const display_name=document.getElementById('nameInput').value.trim();const username=document.getElementById('usernameInput').value.trim();const bio=document.getElementById('bioInput').value.trim();if(!display_name||!username)return alert('Name and username are required.');const q=await sb.from('user_profiles').select('id').eq('username',username).neq('id',user.id).maybeSingle();if(q.data)return alert('That username is already taken.');const up=await sb.from('user_profiles').update({display_name,username,bio,avatar_url}).eq('id',user.id);if(up.error)return alert(up.error.message);const np=document.getElementById('passwordInput').value;if(np){const pw=await sb.auth.updateUser({password:np});if(pw.error)return alert('Profile saved, but password change failed: '+pw.error.message)}await loadUser();document.getElementById('passwordInput').value='';alert('Settings saved.')}
async function logout(){await sb.auth.signOut();document.getElementById('welcome').style.display='flex';showSection('home')}
function showSection(id){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function renderTutorials(){const q=(document.getElementById('search').value||'').toLowerCase();const list=window.siteData.tutorials.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q));document.getElementById('tutorialGrid').innerHTML=list.map((x,i)=>`<article class="tutorial"><div class="eyebrow">${String(i+1).padStart(2,'0')}</div><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p><a href="${defaultLink()}" target="_blank">Open Tutorial →</a></article>`).join('')||'<div class="card">No tutorial found.</div>'}
function defaultLink(){return window.siteData.channel||'https://t.me/+VeysP6zpQI9kZTJl'}
function renderSocial(){document.getElementById('socialGrid').innerHTML=window.siteData.social.map(x=>`<a class="social-btn" href="${x[1]}" target="_blank">${x[2]} &nbsp; ${esc(x[0])}</a>`).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadSettings(){window.siteData={...defaults,channel:'https://t.me/+VeysP6zpQI9kZTJl'};const {data,error}=await sb.from('site_settings').select('data').eq('id','main').maybeSingle();if(!error&&data?.data){window.siteData={...window.siteData,...data.data}}document.getElementById('aboutText').textContent=window.siteData.about||defaults.about;renderTutorials();renderSocial()}
(async()=>{await loadSettings();const {data:{session}}=await sb.auth.getSession();if(session)await loadUser();else document.getElementById('welcome').style.display='flex';sb.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN')loadUser()})})();
